import json


class StreamingCOCOWriter:
    """
    Used to store individual image coco formatted prediction results to a single json file
    in a memory efficient way
    """

    def __init__(self, filepath, categories):
        """
        categories: list of dicts, e.g.,
        [{"id": 0, "name": "car"}, {"id": 1, "name": "person"}]
        """
        self.filepath = filepath
        self.categories = categories
        self.file = open(filepath, 'w')

        # This will hold our image metadata (~100 bytes per image, perfectly safe for memory)
        self.images = []

        self.annotation_id = 1
        self.first_annotation = True

        # Start the JSON object and immediately open the 'annotations' array.
        self.file.write('{\n  "annotations": [\n')

    def add_image_and_predictions(self, image_id, file_name, width, height, sahi_predictions):
        """
        Streams predictions for a single image directly to disk.
        sahi_predictions: The list of dicts from the DB (generated by SAHI's to_coco_predictions)
        """
        # 1. Keep image metadata in memory
        self.images.append({
            "id": image_id,
            "file_name": file_name,  # Crucial: This should match the name in your CVAT manifest (e.g., "image_1.dzi")
            "width": width,
            "height": height
        })

        # 2. Stream the massive annotation payloads directly to disk
        for ann in sahi_predictions:
            # Standard COCO requires a unique ID for every single annotation.
            # SAHI's output might omit this, so we inject it here.
            ann["id"] = self.annotation_id
            self.annotation_id += 1

            # Format and write this single annotation dict
            prefix = '' if self.first_annotation else ',\n'
            self.file.write(prefix + '    ' + json.dumps(ann))
            self.first_annotation = False

    def close(self):
        """Finalizes the file by appending the stored images and categories."""
        # Close the annotations array
        self.file.write('\n  ],\n')

        # Write the lightweight images list
        self.file.write('  "images": ' + json.dumps(self.images, indent=4) + ',\n')

        # Write the categories
        self.file.write('  "categories": ' + json.dumps(self.categories, indent=4) + '\n')

        # Close the main JSON object
        self.file.write('}\n')
        self.file.close()
        print(f"Successfully saved streamed COCO annotations to {self.filepath}")
